In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler

In [6]:

diabetes_df = pd.read_csv("../data/raw/diabetes.csv")
heart_df = pd.read_csv("../data/raw/heartattack.csv")

diabetes_df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [7]:
heart_df.head()

,Patient_ID,State_Name,Age,Gender,Diabetes,Hypertension,Obesity,Smoking,Alcohol_Consumption,Physical_Activity,...,Diastolic_BP,Air_Pollution_Exposure,Family_History,Stress_Level,Healthcare_Access,Heart_Attack_History,Emergency_Response_Time,Annual_Income,Health_Insurance,Heart_Attack_Risk
0,1,Rajasthan,42,Female,0,0,1,1,0,0,...,119,1,0,4,0,0,157,611025,0,0
1,2,Himachal Pradesh,26,Male,0,0,0,0,1,1,...,115,0,0,7,0,0,331,174527,0,0
2,3,Assam,78,Male,0,0,1,0,0,1,...,117,0,1,10,1,0,186,1760112,1,0
3,4,Odisha,58,Male,1,0,1,0,0,1,...,65,0,0,1,1,1,324,1398213,0,0
4,5,Karnataka,22,Male,0,0,0,0,0,1,...,109,0,0,9,0,0,209,97987,0,1

In [8]:
print("Diabetes Info:\n")
diabetes_df.info()

print("\nHeart Attack Info:\n")
heart_df.info()

Diabetes Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

Heart Attack Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               10000 non-null  int64
 1   State_Name               10000 non-null  object
 2   Age                      10000 non-null  int64
 3   Gender                   10000 non-null  object
 4   Diabetes                 10000 non-null  int64
 5   Hypertension             10000 non-null  int64
 6   Obesity                  10000 non-null  int64
 7   Smoking                  10000 non-null  int64
 8   Alcohol_Consumption      10000 non-null  int64
 9   Physical_Activity        10000 non-null  int64
 10  Diet_Score               10000 non-null  int64
 11  Cholesterol_Level        10000 non-null  int64
 12  Triglyceride_Level       10000 non-null  int64
 13  LDL_Level                10000 non-null  int64
 14  HDL_Level                10000 non-null  int64
 15  Systolic_BP              10000 non-null  int64
 16  Diastolic_BP             10000 non-null  int64
 17  Air_Pollution_Exposure   10000 non-null  int64
 18  Family_History           10000 non-null  int64
 19  Stress_Level             10000 non-null  int64
 20  Healthcare_Access        10000 non-null  int64
 21  Heart_Attack_History     10000 non-null  int64
 22  Emergency_Response_Time  10000 non-null  int64
 23  Annual_Income            10000 non-null  int64
 24  Health_Insurance         10000 non-null  int64
 25  Heart_Attack_Risk        10000 non-null  int64
dtypes: int64(24), object(2)
memory usage: 2.0+ MB

In [9]:
print("Diabetes Missing Values:\n")
print(diabetes_df.isnull().sum())

print("\nHeart Attack Missing Values:\n")
print(heart_df.isnull().sum())

Diabetes Missing Values:

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

Heart Attack Missing Values:

Patient_ID                 0
State_Name                 0
Age                        0
Gender                     0
Diabetes                   0
Hypertension               0
Obesity                    0
Smoking                    0
Alcohol_Consumption        0
Physical_Activity          0
Diet_Score                 0
Cholesterol_Level          0
Triglyceride_Level         0
LDL_Level                  0
HDL_Level                  0
Systolic_BP                0
Diastolic_BP               0
Air_Pollution_Exposure     0
Family_History             0
Stress_Level               0
Healthcare_Access          0
Heart_Attack_History       0
Emergency_Response_Time    0
Annual_Income              0
Health_Insurance           0
Heart_Attack_Risk          0
dtype: int64

In [10]:

diabetes_df = diabetes_df.drop(columns=[
    "HbA1c_level",
    "blood_glucose_level"
])

diabetes_df.head()

   gender   age  hypertension  heart_disease smoking_history    bmi  diabetes
0  Female  80.0             0              1           never  25.19         0
1  Female  54.0             0              0         No Info  27.32         0
2    Male  28.0             0              0           never  27.32         0
3  Female  36.0             0              0         current  23.45         0
4    Male  76.0             1              1         current  20.14         0

In [15]:
# Drop useless / noisy columns
heart_df = heart_df.drop(columns=[
    "Patient_ID",
    "State_Name",
    "Emergency_Response_Time",
    "Annual_Income",
    "Healthcare_Access",
    "Heart_Attack_History",
    "Stress_Level",
    "Air_Pollution_Exposure",   
    "Diet_Score",  
    "Triglyceride_Level",
    "LDL_Level",
    "HDL_Level",
    "Health_Insurance"
])

# Preview after drop
heart_df.head()

KeyError: "['Patient_ID', 'State_Name', 'Emergency_Response_Time', 'Annual_Income', 'Healthcare_Access', 'Heart_Attack_History', 'Stress_Level', 'Air_Pollution_Exposure', 'Diet_Score', 'Triglyceride_Level', 'LDL_Level', 'HDL_Level', 'Health_Insurance'] not found in axis"

In [16]:
heart_df = heart_df.drop(columns=["Cholesterol_Level"])

# Preview after drop
heart_df.head()

,Age,Gender,Diabetes,Hypertension,Obesity,Smoking,Alcohol_Consumption,Physical_Activity,Systolic_BP,Diastolic_BP,Family_History,Heart_Attack_Risk
0,42,Female,0,0,1,1,0,0,93,119,0,0
1,26,Male,0,0,0,0,1,1,134,115,0,0
2,78,Male,0,0,1,0,0,1,104,117,1,0
3,58,Male,1,0,1,0,0,1,91,65,0,0
4,22,Male,0,0,0,0,0,1,141,109,0,1

In [17]:
print("Diabetes Columns:\n", diabetes_df.columns)
print("\nHeart Columns:\n", heart_df.columns)

Diabetes Columns:
 Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'diabetes'],
      dtype='object')

Heart Columns:
 Index(['Age', 'Gender', 'Diabetes', 'Hypertension', 'Obesity', 'Smoking',
       'Alcohol_Consumption', 'Physical_Activity', 'Systolic_BP',
       'Diastolic_BP', 'Family_History', 'Heart_Attack_Risk'],
      dtype='object')

In [18]:
diabetes_df.columns = diabetes_df.columns.str.lower()
heart_df.columns = heart_df.columns.str.lower()

In [19]:
# Create encoders
le = LabelEncoder()

# Diabetes dataset
diabetes_df['gender'] = le.fit_transform(diabetes_df['gender'])
diabetes_df['smoking_history'] = le.fit_transform(diabetes_df['smoking_history'])

# Heart dataset
heart_df['gender'] = le.fit_transform(heart_df['gender'])
heart_df['smoking'] = le.fit_transform(heart_df['smoking'])
heart_df['alcohol_consumption'] = le.fit_transform(heart_df['alcohol_consumption'])
heart_df['physical_activity'] = le.fit_transform(heart_df['physical_activity'])
heart_df['family_history'] = le.fit_transform(heart_df['family_history'])