In [1]:
import pandas as pd

In [2]:
diabetes_df = pd.read_csv("../data/raw/diabetes.csv")

In [3]:
print("Shape:", diabetes_df.shape)
print("\nColumns:\n", diabetes_df.columns)
print("\nMissing values:\n", diabetes_df.isnull().sum())
diabetes_df.head()

Shape: (100000, 9)

Columns:
 Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

Missing values:
 gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [4]:
diabetes_df.columns = diabetes_df.columns.str.lower().str.strip()
print(diabetes_df.columns)

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'hba1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [5]:

print(diabetes_df["diabetes"].value_counts())
print("\nData types:\n", diabetes_df.dtypes)

diabetes
0    91500
1     8500
Name: count, dtype: int64

Data types:
 gender                  object
age                    float64
hypertension             int64
heart_disease            int64
smoking_history         object
bmi                    float64
hba1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object

In [6]:

categorical_cols = diabetes_df.select_dtypes(include=["object"]).columns.tolist()
numeric_cols = diabetes_df.select_dtypes(exclude=["object"]).columns.tolist()
print("Categorical:", categorical_cols)
print("Numeric:", numeric_cols)

Categorical: ['gender', 'smoking_history']
Numeric: ['age', 'hypertension', 'heart_disease', 'bmi', 'hba1c_level', 'blood_glucose_level', 'diabetes']

In [ ]:
diabetes_df = pd.get_dummies(
    diabetes_df,
    columns=categorical_cols,
    drop_first=True
)

diabetes_df.head()

,age,hypertension,heart_disease,bmi,hba1c_level,blood_glucose_level,diabetes,gender_Male,gender_Other,smoking_history_current,smoking_history_ever,smoking_history_former,smoking_history_never,smoking_history_not current
0,80.0,0,1,25.19,6.6,140,0,False,False,False,False,False,True,False
1,54.0,0,0,27.32,6.6,80,0,False,False,False,False,False,False,False
2,28.0,0,0,27.32,5.7,158,0,True,False,False,False,False,True,False
3,36.0,0,0,23.45,5.0,155,0,False,False,True,False,False,False,False
4,76.0,1,1,20.14,4.8,155,0,True,False,True,False,False,False,False

In [8]:
bool_cols = diabetes_df.select_dtypes(include="bool").columns
diabetes_df[bool_cols] = diabetes_df[bool_cols].astype(int)